// Mock data for local development, translated from the Claude Design handoff
// prototype (design_handoff_parcel_crm/Parcel CRM.dc.html, the `LEADS` array).
// Timestamps are relative to NOW at import time so the "wait" indicator always
// renders sensible values. Replace with real data once wired to Supabase/GHL.

import type { Draft, Lead, Message, SystemNote } from "./types";

const NOW = Date.now();
const MIN = 60_000;
const HOUR = 60 * MIN;
const DAY = 24 * HOUR;
const iso = (msAgo: number) => new Date(NOW - msAgo).toISOString();

function thread(msgs: Array<Omit<Message, "id">>): Message[] {
  return msgs.map((m, i) => ({ id: `m${i}`, ...m }));
}

function notes(items: Array<Omit<SystemNote, "id">>): SystemNote[] {
  return items.map((n, i) => ({ id: `n${i}`, ...n }));
}

function drafts(items: Array<Omit<Draft, "id">>): Draft[] {
  return items.map((d, i) => ({ id: `d${i}`, ...d }));
}

export const LEADS: Lead[] = [
  {
    id: "l1",
    name: "Dwayne Prather",
    phone: "(931) 555-0142",
    county: "Maury",
    acreage: "42.0",
    stage: "Negotiating",
    stageHistory: [
      { stage: "New", at: iso(3 * DAY) },
      { stage: "Engaging", at: iso(2 * DAY) },
      { stage: "Negotiating", at: iso(3 * HOUR) },
    ],
    triageBucket: "hot_lead_candidate",
    triageMatched: "$850,000",
    triageReason: "Competing offer, time-pressured (rumo F).",
    lastMessageBody:
      "$850,000 or don't waste my time. Already have an offer at $800k — beat it by $50k.",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(2 * MIN),
    unreadCount: 2,
    assignedTo: "a",
    tags: ["maury county, tn"],
    notes: notes([
      { body: "TRIAGE — hot: competing offer cited, comps-first before replying.", at: iso(3 * HOUR), author: "triage-inbox" },
    ]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot in Columbia?", at: iso(5 * DAY), sender: "automation" },
      { direction: "inbound", body: "Depends what you're offering.", at: iso(4 * DAY) },
      { direction: "outbound", body: "Checked with my partners, we'd be at $750,000. We cover closing costs and can move quickly.", at: iso(3 * HOUR), sender: "a" },
      { direction: "inbound", body: "$850,000 or don't waste my time. Already have an offer at $800k — beat it by $50k.", at: iso(2 * MIN) },
    ]),
    dossier: {
      verdict: "NEGOTIATE",
      gapOverMao: "+18%",
      rationale: "Ask sits above MAO but under 1.35x — worth one more round with real comps.",
      opening: 620000,
      target: 690000,
      walkAway: 720000,
      sellerAsk: 850000,
      fmv: 782000,
      eyeballScore: 81,
      parcelId: "058 042A 011.00",
      deedAcres: 42.0,
      zoning: "Residential / Ag",
      structures: "None — vacant",
      diligence: [
        { label: "Road access", detail: "Frontage confirmed, TIGER layer", status: "ok" },
        { label: "Septic / soils", detail: "Somewhat limited, SSURGO", status: "caution" },
        { label: "Wetlands", detail: "None mapped", status: "ok" },
        { label: "Flood zone", detail: "Zone X, outside 100yr", status: "ok" },
      ],
      nextQuestion: "Ask if the competing offer is in writing / under contract already.",
      dealKillers: ["Price anchored to a claimed competing offer — verify before matching", "Timing: he wants this closed fast"],
    },
  },
  {
    id: "l2",
    name: "Rhonda Beckett",
    phone: "(615) 555-0188",
    county: "Williamson",
    acreage: "12.3",
    stage: "Ready for Research",
    stageHistory: [
      { stage: "New", at: iso(2 * DAY) },
      { stage: "Engaging", at: iso(20 * HOUR) },
      { stage: "Ready for Research", at: iso(14 * MIN) },
    ],
    triageBucket: "hot_lead_candidate",
    triageMatched: "offering",
    triageReason: "Asked our number directly — motivation + property confirmed.",
    lastMessageBody: "Maybe. What are you offering for the 12 acres off Gateway Rd?",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(14 * MIN),
    unreadCount: 1,
    assignedTo: null,
    tags: ["williamson county, tn"],
    notes: notes([
      { body: "opening-script: confirmed lot, asked structure/utilities, motivation.", at: iso(20 * HOUR), author: "opening-script" },
      { body: "TRIAGE — hot: asking price directly, ready for dossier.", at: iso(14 * MIN), author: "triage-inbox" },
    ]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot off Gateway Rd?", at: iso(2 * DAY), sender: "automation" },
      { direction: "inbound", body: "Possibly, who is this exactly", at: iso(20 * HOUR) },
      { direction: "outbound", body: "Myself and some business partners, not an agent. Is there a house on it or is it vacant? And what's got you thinking about selling now?", at: iso(20 * HOUR), sender: "automation" },
      { direction: "inbound", body: "Vacant. Just don't need it anymore.", at: iso(15 * HOUR) },
      { direction: "inbound", body: "Maybe. What are you offering for the 12 acres off Gateway Rd?", at: iso(14 * MIN) },
    ]),
    dossier: null,
  },
  {
    id: "l3",
    name: "Earl Hutchins",
    phone: "(931) 555-0209",
    county: "Marshall",
    acreage: "8.5",
    stage: "Engaging",
    stageHistory: [{ stage: "New", at: iso(30 * HOUR) }, { stage: "Engaging", at: iso(22 * MIN) }],
    triageBucket: "needs_ai",
    triageMatched: null,
    triageReason: "Wants to know who's texting — trust question, no price yet.",
    lastMessageBody: "Who is this? what do you want with my land",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(22 * MIN),
    unreadCount: 1,
    assignedTo: null,
    tags: ["marshall county, tn"],
    notes: notes([{ body: "TRIAGE — needs_andre: legitimacy question (rumo K), needs a real reply.", at: iso(22 * MIN), author: "triage-inbox" }]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot in Lewisburg?", at: iso(30 * HOUR), sender: "automation" },
      { direction: "inbound", body: "Who is this? what do you want with my land", at: iso(22 * MIN) },
    ]),
    dossier: null,
  },
  {
    id: "l4",
    name: "Patrice Dunlap",
    phone: "(615) 555-0173",
    county: "Rutherford",
    acreage: "27.0",
    stage: "Qualifying",
    stageHistory: [{ stage: "New", at: iso(5 * DAY) }, { stage: "Qualifying", at: iso(4 * DAY) }],
    triageBucket: "hot_lead_candidate",
    triageMatched: "3k an acre",
    triageReason: "Price signal, still discovering frontage/access.",
    lastMessageBody: "Around 3k an acre if the price is right. Its got road frontage.",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(1 * HOUR),
    unreadCount: 0,
    assignedTo: "b",
    tags: ["rutherford county, tn"],
    notes: notes([]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot in Rutherford?", at: iso(5 * DAY), sender: "automation" },
      { direction: "inbound", body: "Around 3k an acre if the price is right. Its got road frontage.", at: iso(1 * HOUR) },
      { direction: "outbound", body: "Got it — is it all one parcel, and does it have utilities at the road?", at: iso(58 * MIN), sender: "b" },
    ]),
    dossier: null,
  },
  {
    id: "l5",
    name: "Sue-Ann Kettle",
    phone: "(931) 555-0256",
    county: "Bedford",
    acreage: "70.0",
    stage: "Negotiating",
    stageHistory: [{ stage: "New", at: iso(2 * DAY) }, { stage: "Negotiating", at: iso(1 * HOUR) }],
    triageBucket: "possible_rumo_j",
    triageMatched: "$25,000,000",
    triageReason: "Extreme price + explicit dismissal (\"we will walk away\") — flagged, not auto-discarded.",
    lastMessageBody: "Sure! 70 acres, working dairy farm. $25,000,000. We will walk away.",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(1 * HOUR),
    unreadCount: 1,
    assignedTo: null,
    tags: ["bedford county, tn"],
    notes: notes([{ body: "TRIAGE — possible_rumo_j: preço absurdo (>$300k/acre) + \"we will walk away\". Revisar antes de tratar como quente.", at: iso(1 * HOUR), author: "triage-inbox" }]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot in Bedford?", at: iso(2 * DAY), sender: "automation" },
      { direction: "inbound", body: "Sure! 70 acres, working dairy farm. $25,000,000. We will walk away.", at: iso(1 * HOUR) },
    ]),
    dossier: null,
  },
  {
    id: "l6",
    name: "Marcus Bly",
    phone: "(423) 555-0311",
    county: "Lincoln",
    acreage: "19.4",
    stage: "Needs Triage",
    stageHistory: [{ stage: "New", at: iso(2 * DAY) }],
    triageBucket: "needs_ai",
    triageMatched: null,
    triageReason: "\"No lowball offers\" alone has no price — could be rumo H starting, needs a human read.",
    lastMessageBody: "No lowball offers",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(2 * HOUR),
    unreadCount: 1,
    assignedTo: null,
    tags: ["lincoln county, tn"],
    notes: notes([]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot in Fayetteville?", at: iso(2 * DAY), sender: "automation" },
      { direction: "inbound", body: "No lowball offers", at: iso(2 * HOUR) },
    ]),
    dossier: null,
  },
  {
    id: "l7",
    name: "Delia Frost",
    phone: "(615) 555-0290",
    county: "Wilson",
    acreage: "5.1",
    stage: "New",
    stageHistory: [{ stage: "New", at: iso(3 * HOUR) }],
    triageBucket: null,
    lastMessageBody: "(no reply yet — 3 texts sent)",
    lastMessageDirection: "outbound",
    lastMessageAt: iso(3 * HOUR),
    unreadCount: 0,
    assignedTo: null,
    tags: ["wilson county, tn"],
    notes: notes([]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot in Lebanon?", at: iso(3 * HOUR), sender: "automation" },
      { direction: "outbound", body: "Hello, this is Felipe just wanted to check in to see if you got my last text?", at: iso(2 * HOUR), sender: "automation" },
      { direction: "outbound", body: "Hey it's Felipe, is that lot in Lebanon available?", at: iso(1 * HOUR), sender: "automation" },
    ]),
    dossier: null,
  },
  {
    id: "l8",
    name: "Otis Ramsey",
    phone: "(931) 555-0334",
    county: "Giles",
    acreage: "33.2",
    stage: "Engaging",
    stageHistory: [{ stage: "New", at: iso(4 * DAY) }, { stage: "Engaging", at: iso(3 * HOUR) }],
    triageBucket: "needs_ai",
    lastMessageBody: "What are you looking to do with it?",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(3 * HOUR),
    unreadCount: 0,
    assignedTo: "a",
    tags: ["giles county, tn"],
    notes: notes([]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot in Pulaski?", at: iso(4 * DAY), sender: "automation" },
      { direction: "inbound", body: "What are you looking to do with it?", at: iso(3 * HOUR) },
      { direction: "outbound", body: "Mostly holding, some infill later. Is it zoned for residential and does it have utilities at the road?", at: iso(2 * HOUR), sender: "a" },
    ]),
    dossier: null,
  },
  {
    id: "l9",
    name: "Brenda Cole",
    phone: "(615) 555-0377",
    county: "Maury",
    acreage: "15.0",
    stage: "Proposal Sent",
    stageHistory: [{ stage: "New", at: iso(6 * DAY) }, { stage: "Proposal Sent", at: iso(5 * HOUR) }],
    triageBucket: "hot_lead_candidate",
    lastMessageBody: "Send me the paperwork and I will look it over this weekend.",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(5 * HOUR),
    unreadCount: 0,
    assignedTo: "b",
    tags: ["maury county, tn"],
    notes: notes([{ body: "seller-dossier: proposta enviada, $210k, aguardando retorno.", at: iso(6 * HOUR), author: "seller-dossier" }]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hi Brenda, discussed with my partners — we can do $210,000 cash, as-is, we cover closing costs. I'll send a simple one-page agreement.", at: iso(6 * HOUR), sender: "b" },
      { direction: "inbound", body: "Send me the paperwork and I will look it over this weekend.", at: iso(5 * HOUR) },
    ]),
    dossier: {
      verdict: "PURSUE",
      gapOverMao: "-4%",
      rationale: "Ask converged under MAO — clean deal, no further negotiation needed.",
      opening: 190000,
      target: 205000,
      walkAway: 218000,
      sellerAsk: 210000,
      fmv: 236000,
      eyeballScore: 74,
      parcelId: "047 011.02",
      deedAcres: 15.0,
      zoning: "Residential",
      structures: "None — vacant",
      diligence: [
        { label: "Road access", detail: "Frontage confirmed", status: "ok" },
        { label: "Septic / soils", detail: "Not limited, SSURGO", status: "ok" },
        { label: "Wetlands", detail: "None mapped", status: "ok" },
        { label: "Flood zone", detail: "Zone X", status: "ok" },
      ],
      nextQuestion: "Confirm title company preference before sending final contract.",
      dealKillers: [],
    },
  },
  {
    id: "l10",
    name: "Hank Delaney",
    phone: "(423) 555-0402",
    county: "Coffee",
    acreage: "48.0",
    stage: "Under Contract",
    stageHistory: [{ stage: "New", at: iso(10 * DAY) }, { stage: "Under Contract", at: iso(1 * DAY) }],
    triageBucket: "hot_lead_candidate",
    lastMessageBody: "Signed & sent back. When does the title company reach out?",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(1 * DAY),
    unreadCount: 0,
    assignedTo: "a",
    tags: ["coffee county, tn"],
    notes: notes([]),
    drafts: [],
    messages: thread([
      { direction: "inbound", body: "Signed & sent back. When does the title company reach out?", at: iso(1 * DAY) },
      { direction: "outbound", body: "Perfect, thank you. They'll reach out within 2 business days to start the title search.", at: iso(23 * HOUR), sender: "a" },
    ]),
    dossier: null,
  },
  {
    id: "l11",
    name: "Gil Auburn",
    phone: "(931) 555-0455",
    county: "Lawrence",
    acreage: "6.0",
    stage: "Discarded",
    stageHistory: [{ stage: "New", at: iso(2 * DAY) }, { stage: "Discarded", at: iso(1 * DAY) }],
    triageBucket: "cancelled",
    triageMatched: "Not interested",
    lastMessageBody: "Not interested. Not selling, take me off your list.",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(1 * DAY),
    unreadCount: 0,
    assignedTo: null,
    tags: ["lawrence county, tn"],
    notes: notes([{ body: "TRIAGE — cancelled: recusa dura, sem motivo.", at: iso(1 * DAY), author: "triage-inbox" }]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot in Lawrenceburg?", at: iso(2 * DAY), sender: "automation" },
      { direction: "inbound", body: "Not interested. Not selling, take me off your list.", at: iso(1 * DAY) },
    ]),
    dossier: null,
  },
  {
    id: "l12",
    name: "Unknown",
    phone: "(615) 555-0488",
    county: "Rutherford",
    acreage: "—",
    stage: "Discarded",
    stageHistory: [{ stage: "New", at: iso(2 * DAY) }, { stage: "Discarded", at: iso(2 * DAY) }],
    triageBucket: "cancelled_wrong_number",
    lastMessageBody: "You have the wrong number",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(2 * DAY),
    unreadCount: 0,
    assignedTo: null,
    tags: ["rutherford county, tn"],
    notes: notes([{ body: "TRIAGE — wrong_number: lista suja, não recusa de venda.", at: iso(2 * DAY), author: "triage-inbox" }]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot in Murfreesboro?", at: iso(2 * DAY), sender: "automation" },
      { direction: "inbound", body: "You have the wrong number", at: iso(2 * DAY) },
    ]),
    dossier: null,
  },
  {
    id: "l13",
    name: "T. Vann",
    phone: "(423) 555-0511",
    county: "Franklin",
    acreage: "22.5",
    stage: "Do Not Contact",
    stageHistory: [{ stage: "New", at: iso(3 * DAY) }, { stage: "Do Not Contact", at: iso(2 * DAY) }],
    triageBucket: "do_not_contact",
    lastMessageBody: "STOP",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(2 * DAY),
    unreadCount: 0,
    assignedTo: null,
    tags: ["franklin county, tn"],
    notes: notes([{ body: "TRIAGE — do_not_contact: opt-out, GHL já suprime automaticamente.", at: iso(2 * DAY), author: "triage-inbox" }]),
    drafts: [],
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot in Winchester?", at: iso(3 * DAY), sender: "automation" },
      { direction: "inbound", body: "STOP", at: iso(2 * DAY) },
    ]),
    dossier: null,
  },
  {
    id: "l14",
    name: "Corey Nix",
    phone: "(931) 555-0544",
    county: "Maury",
    acreage: "11.7",
    stage: "Engaging",
    stageHistory: [{ stage: "New", at: iso(6 * HOUR) }, { stage: "Engaging", at: iso(4 * HOUR) }],
    triageBucket: "needs_ai",
    lastMessageBody: "How much are we talking here?",
    lastMessageDirection: "inbound",
    lastMessageAt: iso(4 * HOUR),
    unreadCount: 2,
    assignedTo: null,
    tags: ["maury county, tn"],
    notes: notes([]),
    drafts: drafts([
      { text: "Appreciate you asking directly — before I give you a number, is there a house or structure on it, or is it vacant? Helps me get you the right figure.", status: "pending", createdAt: iso(3 * HOUR) },
    ]),
    messages: thread([
      { direction: "outbound", body: "Hey, this is Felipe. I was in the area and I work for an investor who buys land, would you consider selling the lot in Columbia?", at: iso(6 * HOUR), sender: "automation" },
      { direction: "inbound", body: "How much are we talking here?", at: iso(4 * HOUR) },
    ]),
    dossier: null,
  },
];

export function getLead(id: string): Lead | undefined {
  return LEADS.find((l) => l.id === id);
}
